# Generated by Django 3.2.7 on 2021-09-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Priview',
            new_name='Preview',
        ),
    ]
