# Generated by Django 3.2.7 on 2021-09-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_liveurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='techs',
            field=models.ManyToManyField(blank=True, to='portfolio.ProjectTech'),
        ),
    ]
