# Generated by Django 3.2.7 on 2023-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
